// js/data.js
// All static data for weapons, tools, consumables, and tarot cards.

const WEAPONS = [
  {name:"Bornheim No. 3",size:1,ammo:"Compact",category:"pistol"},
  {name:"Bornheim No. 3 Extended",size:1,ammo:"Compact",category:"pistol"},
  {name:"Bornheim No. 3 Silencer",size:1,ammo:"Compact",category:"pistol"},
  {name:"Conversion",size:1,ammo:"Compact",category:"pistol"},
  {name:"Conversion Chain Pistol",size:1,ammo:"Compact",category:"pistol"},
  {name:"Hand Crossbow",size:1,ammo:"Special",category:"special"},
  {name:"LeMat",size:1,ammo:"Compact",category:"pistol"},
  {name:"Nagant M1895",size:1,ammo:"Compact",category:"pistol"},
  {name:"Nagant M1895 Silencer",size:1,ammo:"Compact",category:"pistol"},
  {name:"New Army",size:1,ammo:"Compact",category:"pistol"},
  {name:"New Army Swift",size:1,ammo:"Compact",category:"pistol"},
  {name:"Officer",size:1,ammo:"Compact",category:"pistol"},
  {name:"Officer Brawler",size:1,ammo:"Compact",category:"pistol"},
  {name:"Pax",size:1,ammo:"Medium",category:"pistol"},
  {name:"Pax Claw",size:1,ammo:"Medium",category:"pistol"},
  {name:"Pax Trueshot",size:1,ammo:"Medium",category:"pistol"},
  {name:"Scottfield",size:1,ammo:"Medium",category:"pistol"},
  {name:"Scottfield Brawler",size:1,ammo:"Medium",category:"pistol"},
  {name:"Scottfield Spitfire",size:1,ammo:"Medium",category:"pistol"},
  {name:"Scottfield Swift",size:1,ammo:"Medium",category:"pistol"},
  {name:"Sparks Pistol",size:1,ammo:"Long",category:"pistol"},
  {name:"Sparks Pistol Silencer",size:1,ammo:"Long",category:"pistol"},
  {name:"Baseball Bat",size:1,ammo:"Melee",category:"melee"},
  {name:"Cavalry Saber",size:1,ammo:"Melee",category:"melee"},
  {name:"Machete",size:1,ammo:"Melee",category:"melee"},
  {name:"Bomb Launcher",size:2,ammo:"Special",category:"special"},
  {name:"Bornheim No. 3 Match",size:2,ammo:"Compact",category:"pistol"},
  {name:"Centennial Pointman",size:2,ammo:"Medium",category:"rifle"},
  {name:"Centennial Shorty",size:2,ammo:"Medium",category:"rifle"},
  {name:"Centennial Shorty Silencer",size:2,ammo:"Medium",category:"rifle"},
  {name:"Chu Ko Nu",size:2,ammo:"Special",category:"special"},
  {name:"Combat Axe",size:2,ammo:"Melee",category:"melee"},
  {name:"Dolch 96",size:2,ammo:"Special",category:"pistol"},
  {name:"Dolch 96 Bullseye",size:2,ammo:"Special",category:"pistol",scoped:true},
  {name:"Dolch 96 Claw",size:2,ammo:"Special",category:"pistol"},
  {name:"Drilling Hatchet",size:2,ammo:"Medium",category:"rifle"},
  {name:"Drilling Shorty",size:2,ammo:"Medium",category:"rifle"},
  {name:"Flame Rifle",size:2,ammo:"Special",category:"special"},
  {name:"Haymaker",size:2,ammo:"Long",category:"pistol"},
  {name:"Katana",size:2,ammo:"Melee",category:"melee"},
  {name:"Mosin Obrez",size:2,ammo:"Special Long",category:"rifle"},
  {name:"Mosin Obrez Extended",size:2,ammo:"Special Long",category:"rifle"},
  {name:"Mosin Obrez Mace",size:2,ammo:"Special Long",category:"rifle"},
  {name:"Nagant M1895 Deadeye",size:2,ammo:"Compact",category:"pistol",scoped:true},
  {name:"Nagant M1895 Precision",size:2,ammo:"Compact",category:"pistol"},
  {name:"Railroad Hammer",size:2,ammo:"Melee",category:"melee"},
  {name:"Rival 78 Mace",size:2,ammo:"Shotgun",category:"shotgun"},
  {name:"Rival 78 Shorty",size:2,ammo:"Shotgun",category:"shotgun"},
  {name:"Romero 77 Hatchet",size:2,ammo:"Shotgun",category:"shotgun"},
  {name:"Romero 77 Shorty",size:2,ammo:"Shotgun",category:"shotgun"},
  {name:"Scottfield Precision",size:2,ammo:"Medium",category:"pistol"},
  {name:"Specter 1882 Shorty",size:2,ammo:"Shotgun",category:"shotgun"},
  {name:"Springfield 1866 Bullseye",size:2,ammo:"Medium",category:"rifle",scoped:true},
  {name:"Springfield 1866 Shorty",size:2,ammo:"Medium",category:"rifle"},
  {name:"Springfield 1866 Striker",size:2,ammo:"Medium",category:"rifle"},
  {name:"Terminus Shorty",size:2,ammo:"Shotgun",category:"shotgun"},
  {name:"Uppercut",size:2,ammo:"Long",category:"pistol"},
  {name:"Vandal 73C",size:2,ammo:"Compact",category:"rifle",auto:true},
  {name:"Vandal 73C Bullseye",size:2,ammo:"Compact",category:"rifle",auto:true,scoped:true},
  {name:"Vandal 73C Striker",size:2,ammo:"Compact",category:"rifle",auto:true},
  {name:"1865 Carbine",size:3,ammo:"Medium",category:"rifle"},
  {name:"1865 Carbine Aperture",size:3,ammo:"Medium",category:"rifle",scoped:true},
  {name:"1865 Carbine Silencer",size:3,ammo:"Medium",category:"rifle"},
  {name:"1890 Cavalry",size:3,ammo:"Long",category:"rifle"},
  {name:"Auto-4 Shorty",size:3,ammo:"Shotgun",category:"shotgun",auto:true},
  {name:"Berthier 1892",size:3,ammo:"Special Long",category:"rifle",auto:true},
  {name:"Berthier 1892 Deadeye",size:3,ammo:"Special Long",category:"rifle",auto:true,scoped:true},
  {name:"Berthier 1892 Marksman",size:3,ammo:"Special Long",category:"rifle",auto:true,scoped:true},
  {name:"Berthier 1892 Riposte",size:3,ammo:"Special Long",category:"rifle",auto:true},
  {name:"Bomb Lance",size:3,ammo:"Special",category:"special"},
  {name:"Dolch 96 Precision",size:3,ammo:"Special",category:"pistol"},
  {name:"Frontier 73C",size:3,ammo:"Compact",category:"rifle",auto:true},
  {name:"Frontier 73C Marksman",size:3,ammo:"Compact",category:"rifle",auto:true,scoped:true},
  {name:"Frontier 73C Silencer",size:3,ammo:"Compact",category:"rifle",auto:true},
  {name:"Hunting Bow",size:3,ammo:"Special",category:"special"},
  {name:"LeMat Carbine",size:3,ammo:"Compact",category:"rifle"},
  {name:"LeMat Carbine Marksman",size:3,ammo:"Compact",category:"rifle",scoped:true},
  {name:"Mosin Obrez Match",size:3,ammo:"Special Long",category:"rifle"},
  {name:"Mosin Obrez Sharpeye",size:3,ammo:"Special Long",category:"rifle"},
  {name:"Officer Carbine",size:3,ammo:"Compact",category:"rifle"},
  {name:"Officer Carbine Deadeye",size:3,ammo:"Compact",category:"rifle",scoped:true},
  {name:"Uppercut Deadeye",size:3,ammo:"Long",category:"pistol",scoped:true},
  {name:"Uppercut Precision",size:3,ammo:"Long",category:"pistol"},
  {name:"Vetterli 71",size:3,ammo:"Medium",category:"rifle"},
  {name:"Vetterli 71 Bayonet",size:3,ammo:"Medium",category:"rifle"},
  {name:"Vetterli 71 Deadeye",size:3,ammo:"Medium",category:"rifle",scoped:true},
  {name:"Vetterli 71 Marksman",size:3,ammo:"Medium",category:"rifle",scoped:true},
  {name:"Vetterli 71 Silencer",size:3,ammo:"Medium",category:"rifle"},
  {name:"Centennial",size:4,ammo:"Medium",category:"rifle"},
  {name:"Centennial Sniper",size:4,ammo:"Medium",category:"rifle",scoped:true},
  {name:"Centennial Trauma",size:4,ammo:"Medium",category:"rifle"},
  {name:"Crossbow",size:4,ammo:"Special",category:"special"},
  {name:"Crossbow Deadeye",size:4,ammo:"Special",category:"special",scoped:true},
  {name:"Drilling",size:4,ammo:"Medium",category:"rifle"},
  {name:"Homestead 78",size:4,ammo:"Shotgun",category:"shotgun"},
  {name:"Infantry 73L",size:4,ammo:"Compact",category:"rifle"},
  {name:"Infantry 73L Bayonet",size:4,ammo:"Compact",category:"rifle"},
  {name:"Infantry 73L Sniper",size:4,ammo:"Compact",category:"rifle",scoped:true},
  {name:"Krag",size:4,ammo:"Special Long",category:"rifle"},
  {name:"Krag Bayonet",size:4,ammo:"Special Long",category:"rifle"},
  {name:"Krag Silencer",size:4,ammo:"Special Long",category:"rifle",scoped:true},
  {name:"Krag Sniper",size:4,ammo:"Special Long",category:"rifle",scoped:true},
  {name:"Lebel 1886",size:4,ammo:"Special Long",category:"rifle"},
  {name:"Lebel 1886 Aperture",size:4,ammo:"Special Long",category:"rifle",scoped:true},
  {name:"Lebel 1886 Marksman",size:4,ammo:"Special Long",category:"rifle",scoped:true},
  {name:"Lebel 1886 Talon",size:4,ammo:"Special Long",category:"rifle"},
  {name:"Mako 1895",size:4,ammo:"Long",category:"rifle"},
  {name:"Mako 1895 Aperture",size:4,ammo:"Long",category:"rifle",scoped:true},
  {name:"Mako 1895 Claw",size:4,ammo:"Long",category:"rifle"},
  {name:"Marathon",size:4,ammo:"Compact",category:"rifle",auto:true},
  {name:"Marathon Swift",size:4,ammo:"Compact",category:"rifle",auto:true},
  {name:"Martini-Henry",size:4,ammo:"Long",category:"rifle"},
  {name:"Martini-Henry Deadeye",size:4,ammo:"Long",category:"rifle",scoped:true},
  {name:"Martini-Henry Ironside",size:4,ammo:"Long",category:"rifle"},
  {name:"Martini-Henry Marksman",size:4,ammo:"Long",category:"rifle",scoped:true},
  {name:"Martini-Henry Riposte",size:4,ammo:"Long",category:"rifle"},
  {name:"Maynard Sniper",size:4,ammo:"Medium",category:"rifle",scoped:true},
  {name:"Mosin-Nagant",size:4,ammo:"Special Long",category:"rifle"},
  {name:"Mosin-Nagant Bayonet",size:4,ammo:"Special Long",category:"rifle"},
  {name:"Mosin-Nagant Sniper",size:4,ammo:"Special Long",category:"rifle",scoped:true},
  {name:"Ranger 73",size:4,ammo:"Compact",category:"rifle"},
  {name:"Ranger 73 Aperture",size:4,ammo:"Compact",category:"rifle",scoped:true},
  {name:"Ranger 73 Swift",size:4,ammo:"Compact",category:"rifle"},
  {name:"Ranger 73 Talon",size:4,ammo:"Compact",category:"rifle"},
  {name:"Rival 78",size:4,ammo:"Shotgun",category:"shotgun"},
  {name:"Rival 78 Trauma",size:4,ammo:"Shotgun",category:"shotgun"},
  {name:"Romero 77",size:4,ammo:"Shotgun",category:"shotgun"},
  {name:"Romero 77 Alamo",size:4,ammo:"Shotgun",category:"shotgun"},
  {name:"Romero 77 Talon",size:4,ammo:"Shotgun",category:"shotgun"},
  {name:"Shredder",size:4,ammo:"Special",category:"special",scarce:true},
  {name:"Slate",size:4,ammo:"Shotgun",category:"shotgun"},
  {name:"Slate Riposte",size:4,ammo:"Shotgun",category:"shotgun"},
  {name:"Sparks",size:4,ammo:"Long",category:"rifle"},
  {name:"Sparks Silencer",size:4,ammo:"Long",category:"rifle"},
  {name:"Sparks Sniper",size:4,ammo:"Long",category:"rifle",scoped:true},
  {name:"Specter 1882",size:4,ammo:"Shotgun",category:"shotgun"},
  {name:"Specter 1882 Bayonet",size:4,ammo:"Shotgun",category:"shotgun"},
  {name:"Springfield 1866",size:4,ammo:"Medium",category:"rifle"},
  {name:"Springfield 1866 Bayonet",size:4,ammo:"Medium",category:"rifle"},
  {name:"Springfield 1866 Marksman",size:4,ammo:"Medium",category:"rifle",scoped:true},
  {name:"Terminus",size:4,ammo:"Shotgun",category:"shotgun"},
  {name:"Vetterli 71 Cyclone",size:4,ammo:"Medium",category:"rifle"},
  {name:"Wildland",size:4,ammo:"Medium",category:"rifle"},
  {name:"Auto-5",size:5,ammo:"Shotgun",category:"shotgun",auto:true},
  {name:"Maynard Sniper Silencer",size:5,ammo:"Medium",category:"rifle",scoped:true},
  {name:"Mosin-Nagant Avtomat",size:5,ammo:"Special Long",category:"rifle",auto:true,scoped:true},
  {name:"Nitro Express",size:5,ammo:"Special",category:"special"}
];

const TOOLS = [
  {name:"First Aid Kit",type:"healing"},
  {name:"Flare Pistol",type:"fire"},
  {name:"Fusees",type:"fire"},
  {name:"Dusters",type:"melee"},
  {name:"Heavy Knife",type:"melee"},
  {name:"Knife",type:"melee"},
  {name:"Knuckle Knife",type:"melee"},
  {name:"Throwing Axes",type:"throwable"},
  {name:"Throwing Knives",type:"throwable"},
  {name:"Throwing Spear",type:"throwable"},
  {name:"Derringer Pennyshot",type:"pocket"},
  {name:"Quad Derringer",type:"pocket"},
  {name:"Alert Trip Mines",type:"trap"},
  {name:"Concertina Trip Mines",type:"trap"},
  {name:"Poison Trip Mines",type:"trap"},
  {name:"Bear Traps",type:"trap"},
  {name:"Choke Bombs",type:"explosive"},
  {name:"Spyglass",type:"utility"},
  {name:"Blank Fire Decoys",type:"distraction"},
  {name:"Decoys",type:"distraction"},
  {name:"Decoy Fuses",type:"distraction"}
];

const CONSUMABLES = [
  {name:"Ammo Box",type:"resupply"},
  {name:"Tool Box",type:"resupply"},
  {name:"Fire Bomb",type:"fire"},
  {name:"Hellfire Bomb",type:"fire"},
  {name:"Liquid Fire Bomb",type:"fire"},
  {name:"Dynamite Stick",type:"explosive"},
  {name:"Dynamite Bundle",type:"explosive"},
  {name:"Waxed Dynamite Stick",type:"explosive"},
  {name:"Big Dynamite Bundle",type:"explosive"},
  {name:"Sticky Bomb",type:"explosive"},
  {name:"Frag Bomb",type:"explosive"},
  {name:"Dark Dynamite Satchel",type:"explosive"},
  {name:"Hive Bomb",type:"explosive"},
  {name:"Poison Bomb",type:"explosive"},
  {name:"Chaos Bomb",type:"explosive"},
  {name:"Antidote Shot",type:"shot"},
  {name:"Antidote Shot (Weak)",type:"shot"},
  {name:"Regeneration Shot",type:"shot"},
  {name:"Regeneration Shot (Weak)",type:"shot"},
  {name:"Stamina Shot",type:"shot"},
  {name:"Stamina Shot (Weak)",type:"shot"},
  {name:"Medical Pack",type:"healing"},
  {name:"Vitality Shot",type:"shot"},
  {name:"Vitality Shot (Weak)",type:"shot"},
  {name:"Recovery Shot",type:"shot"},
  {name:"Stalker Beetle",type:"beetle"},
  {name:"Choke Beetle",type:"beetle"},
  {name:"Fire Beetle",type:"beetle"},
  {name:"Concertina Bomb",type:"explosive"},
  {name:"Flash Bomb",type:"throwable"}
];

const TAROT_CARDS = [
  "The Chariot","The Devil","The Empress","The Fool","The Garden",
  "The Hanged Man","The High Priestess","The Judgement","The Magician",
  "The Moon","The Pathfinder","The Sun","The Tower","The World"
];
